name: Lint markdown
on:
  push:
    paths:
      - "**/*.md"
      - ".github/workflows/lint-md.yml"
  pull_request:
    paths:
      - "**/*.md"
      - ".github/workflows/lint-md.yml"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actionshub/markdownlint@v2.1.5
